### ISSUE TITLE
[FEATURE REQUEST] better way for op/ed ignoring

### ISSUE THREAD

**Issue by jacklimme** [dxing97/subs2cia#6]
Hi, thank you for your works. It has been a great help for creating condensed audio. However, I found it annoying needing to type the fixed timestamp for ignoring because ED timestamp differs from episode to episode. It is possible to implement this feature?

Instead of using fixed timestamp such as ```-I 2m 3m30s```, use ```-I +1m30s``` as a replacement for ```-I 0m 1m30s``` and ```-I -1m30s``` as a replacement for the fixed timestamp of last 1 minute 30 seconds of the video. 

Thank you very much.

**Comment by dxing97** [comment]
A fixed offset from the beginning of the audio track doesn't make much sense since you could just specify `0s`, but specifying ranges relative to the end of the audio track sounds like a good idea. Maybe something like
`-I -1m -0m` to ignore the last minute, 
`-I -2m -1m` to ignore the second to last minute, 
`-I 1m -1m` to ignore everything after the first minute and before the last minute.  
`-I 10m +1m` to ignore the minute after the 10 minute mark
`-I -2m +1m30s` to ignore the first 1m30s in the last 2 minutes
`-I -2m 1m` would do nothing/raise a warning if the audio is longer than 3 minutes

**Comment by dxing97** [comment]
added in v0.3
